# Generated by Django 2.2.5 on 2019-09-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evesde', '0010_auto_20190927_1846'),
        ('eveonline', '0010_alliance_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evesde.EveType')),
                ('average_price', models.FloatField(default=None, null=True)),
                ('adjusted_price', models.FloatField(default=None, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('moon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evesde.EveItem')),
                ('income', models.FloatField(default=None, null=True)),
                ('system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveSolarSystem')),
            ],
            options={
                'permissions': (('access_moonplanner', 'Can access the moonplanner app.'), ('view_all_moons', 'Can see all moons')),
            },
        ),
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('structure_id', models.BigIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonplanner.Moon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.EveType')),
            ],
        ),
        migrations.CreateModel(
            name='MoonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('moon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonplanner.Moon')),
                ('ore_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveType')),
            ],
        ),
        migrations.CreateModel(
            name='MoonDataCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_notification', models.BigIntegerField(default=0, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('decay_time', models.DateTimeField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('moon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonplanner.Moon')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonplanner.Refinery')),
            ],
        ),
        migrations.AddIndex(
            model_name='moonproduct',
            index=models.Index(fields=['moon'], name='moonplanner_moon_id_5b5124_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moonproduct',
            unique_together={('moon', 'ore_type')},
        ),
        migrations.AlterUniqueTogether(
            name='extractevent',
            unique_together={('arrival_time', 'moon')},
        ),
    ]
