# Generated by Django 3.1.6 on 2021-03-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("eveonline", "0014_auto_20210105_1413"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoonPlanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("access_moonplanner", "Can access the moonplanner app"),
                    ("access_our_moons", "Can access our moons and see extractions"),
                    ("access_all_moons", "Can access all moons in the database"),
                    ("upload_moon_scan", "Can upload moon scans"),
                    ("add_mining_corporation", "Can add mining corporation"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ready_time", models.DateTimeField()),
                ("auto_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MiningCorporation",
            fields=[
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mining_corporations",
                        serialize=False,
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moon",
            fields=[
                (
                    "eve_moon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="income",
                        serialize=False,
                        to="eveuniverse.evemoon",
                    ),
                ),
                ("income", models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Refinery",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moonplanner.miningcorporation",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        limit_choices_to={"eve_group_id": 1406},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "moon",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="refinery",
                        to="moonplanner.moon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoonProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "eve_type",
                    models.ForeignKey(
                        default=None,
                        limit_choices_to=models.Q(group__category_id=25),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "moon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="moonplanner.moon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.FloatField()),
                (
                    "eve_type",
                    models.ForeignKey(
                        default=None,
                        limit_choices_to=models.Q(eve_group__eve_category_id=25),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="moonplanner.extraction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extraction",
            name="refinery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extractions",
                to="moonplanner.refinery",
            ),
        ),
    ]
