# Generated by Django 2.2.5 on 2019-09-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0010_auto_20190927_1846'),
        ('moonplaner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moonproduct',
            old_name='type',
            new_name='ore_type',
        ),
        migrations.AlterUniqueTogether(
            name='moonproduct',
            unique_together={('moon', 'ore_type')},
        ),
    ]
