# Generated by Django 3.1.6 on 2021-03-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moonproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
