# Generated by Django 3.1.6 on 2021-03-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refinery",
            old_name="structure_id",
            new_name="id",
        ),
    ]
