# Generated by Django 2.2.5 on 2019-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('access_moonplanner', 'Can access the moonplanner app'), ('view_all_moons', 'Can see all moons in the database'), ('upload_moon_scan', 'Can upload moon scans'))},
        ),
        migrations.AlterField(
            model_name='moon',
            name='income',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
