# Generated by Django 3.1.6 on 2021-03-26 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("moonplanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access the moonplanner app"),
                    (
                        "extractions_access",
                        "Can access extractions and view owned moons",
                    ),
                    ("view_all_moons", "Can view all known moons"),
                    ("upload_moon_scan", "Can upload moon scans"),
                    ("add_corporation", "Can add mining corporations"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="extraction",
            name="started_by",
            field=models.ForeignKey(
                default=None,
                help_text="Eve character who started this extraction",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="value",
            field=models.FloatField(
                default=None,
                help_text="Calculated value estimate",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="moon",
            name="products_updated_at",
            field=models.DateTimeField(
                default=None,
                help_text="Time the last moon survey was uploaded",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moon",
            name="products_updated_by",
            field=models.ForeignKey(
                default=None,
                help_text="User who uploaded the last moon survey",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moon",
            name="value",
            field=models.FloatField(
                default=None,
                help_text="Calculated value estimate",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="refinery",
            name="corporation",
            field=models.ForeignKey(
                help_text="Mining corporation that owns this refinery",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refineries",
                to="moonplanner.miningcorporation",
            ),
        ),
        migrations.AlterField(
            model_name="refinery",
            name="moon",
            field=models.OneToOneField(
                default=None,
                help_text="The moon this refinery is anchored at (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="refinery",
                to="moonplanner.moon",
            ),
        ),
    ]
