# Generated by Django 2.2.5 on 2019-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonplaner', '0002_auto_20190928_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('access_moonplanner', 'Can access the moonplanner app.'), ('view_all_moons', 'Can see all moons'))},
        ),
    ]
