# Generated by Django 2.2.5 on 2019-09-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonplanner', '0002_auto_20190929_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('access_moonplanner', 'Can access the moonplanner app'), ('research_moons', 'Can research all moons in the database'), ('upload_moon_scan', 'Can upload moon scans'))},
        ),
    ]
