# Generated by Django 3.1.6 on 2021-03-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("moonplanner", "0002_extraction_started_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveOreType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eveuniverse.evetype",),
        ),
        migrations.AddField(
            model_name="miningcorporation",
            name="last_update_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="extractionproduct",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="moonplanner.eveoretype",
            ),
        ),
        migrations.AlterField(
            model_name="moonproduct",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="moonplanner.eveoretype",
            ),
        ),
    ]
