# Generated by Django 3.1.6 on 2021-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0002_auto_20210326_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningcorporation",
            name="last_update_ok",
            field=models.BooleanField(
                default=None,
                help_text="True if the last update was successful",
                null=True,
            ),
        ),
    ]
