# Generated by Django 3.1.6 on 2021-03-21 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moonplanner", "0002_moonproduct_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moonproduct",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="moon",
            name="products_updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="moon",
            name="products_updated_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
