# Generated by Django 3.1.6 on 2021-03-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0003_auto_20210326_1213"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractionproduct",
            old_name="eve_type",
            new_name="ore_type",
        ),
        migrations.RenameField(
            model_name="moonproduct",
            old_name="eve_type",
            new_name="ore_type",
        ),
    ]
