# Generated by Django 2.2.5 on 2019-09-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0003_auto_20190930_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refinery",
            name="moon",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="moonplanner.Moon",
            ),
        ),
    ]
