# Generated by Django 3.1.6 on 2021-03-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0014_auto_20210105_1413"),
        ("moonplanner", "0003_auto_20210321_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miningcorporation",
            name="character",
            field=models.ForeignKey(
                default=None,
                help_text="eve character used to sync this corporation from ESI",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="eveonline.evecharacter",
            ),
        ),
    ]
