# Generated by Django 3.1.6 on 2021-03-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_remove_fleetup_permission"),
        ("moonplanner", "0004_auto_20210322_1317"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miningcorporation",
            name="character",
        ),
        migrations.AddField(
            model_name="miningcorporation",
            name="character_ownership",
            field=models.ForeignKey(
                default=None,
                help_text="character used to sync this corporation from ESI",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentication.characterownership",
            ),
        ),
    ]
