# Generated by Django 3.1.6 on 2021-03-27 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0004_auto_20210327_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moon",
            name="value",
            field=models.FloatField(
                db_index=True,
                default=None,
                help_text="Calculated value estimate",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
