# Generated by Django 3.1.6 on 2021-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0004_auto_20210326_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningcorporation",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="disabled corporations are excluded from the update process",
            ),
        ),
        migrations.AlterField(
            model_name="miningcorporation",
            name="last_update_at",
            field=models.DateTimeField(
                default=None, help_text="time of last successful update", null=True
            ),
        ),
    ]
