# Generated by Django 2.2.5 on 2019-09-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evesde", "0014_delete_evename"),
        ("moonplanner", "0005_auto_20190930_2040"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtrationProduct",
            new_name="ExtractionProduct",
        ),
    ]
