# Generated by Django 3.1.6 on 2021-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0005_auto_20210327_1416"),
    ]

    operations = [
        migrations.AddField(
            model_name="moon",
            name="rarity_class",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "None"),
                    (4, "R4"),
                    (8, "R8"),
                    (16, "R16"),
                    (32, "R32"),
                    (64, "R64"),
                ],
                default=0,
            ),
        ),
    ]
