# Generated by Django 3.1.6 on 2021-03-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0006_auto_20210323_1405"),
    ]

    operations = [
        migrations.RenameField(
            model_name="miningcorporation",
            old_name="corporation",
            new_name="eve_corporation",
        ),
    ]
