# Generated by Django 3.1.6 on 2021-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0006_moon_rarity_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moon",
            name="rarity_class",
            field=models.PositiveIntegerField(
                choices=[
                    (0, ""),
                    (4, "R4"),
                    (8, "R8"),
                    (16, "R16"),
                    (32, "R32"),
                    (64, "R64"),
                ],
                default=0,
            ),
        ),
    ]
