# Generated by Django 3.1.6 on 2021-03-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0007_auto_20210327_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="is_jackpot",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
