# Generated by Django 3.1.6 on 2021-03-24 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("moonplanner", "0007_auto_20210323_1808"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moon",
            old_name="income",
            new_name="value",
        ),
        migrations.AddField(
            model_name="extraction",
            name="value",
            field=models.FloatField(
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="extractionproduct",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AlterField(
            model_name="moon",
            name="eve_moon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="known",
                serialize=False,
                to="eveuniverse.evemoon",
            ),
        ),
        migrations.AlterField(
            model_name="moonproduct",
            name="eve_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AlterField(
            model_name="refinery",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
    ]
