# Generated by Django 2.2.5 on 2019-10-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonplanner", "0008_auto_20191019_1733"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moonplanner",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("access_moonplanner", "Can access the moonplanner app"),
                    ("access_our_moons", "Can access our moons and see extractions"),
                    ("access_all_moons", "Can access all moons in the database"),
                    ("upload_moon_scan", "Can upload moon scans"),
                    ("add_mining_corporation", "Can add mining corporation"),
                ),
            },
        ),
    ]
