# Generated by Django 2.2.5 on 2019-09-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('evesde', '0008_auto_20190915_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('moon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evesde.EveItem')),
                ('system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveSolarSystem')),
            ],
            options={
                'permissions': (('view_moonstuff', 'Can access the moonstuff module.'), ('view_all_moons', 'Can see all moons')),
            },
        ),
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('structure_id', models.BigIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonstuff.Moon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evesde.EveType')),
            ],
        ),
        migrations.CreateModel(
            name='MoonDataCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_notification', models.BigIntegerField(default=0, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='MoonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=11)),
                ('moon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonstuff.Moon')),
                ('ore', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveType')),
            ],
            options={
                'unique_together': {('moon', 'ore')},
            },
        ),
        migrations.CreateModel(
            name='ExtractEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('decay_time', models.DateTimeField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('moon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonstuff.Moon')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moonstuff.Refinery')),
            ],
            options={
                'unique_together': {('arrival_time', 'moon')},
            },
        ),
    ]
