# Generated by Django 2.0.9 on 2018-10-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extractevent',
            unique_together={('arrival_time', 'moon')},
        ),
    ]
