# Generated by Django 2.2.5 on 2019-09-26 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0008_auto_20190915_1844'),
        ('moonstuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evesde.EveType')),
                ('average_price', models.FloatField(default=None, null=True)),
                ('adjusted_price', models.FloatField(default=None, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moonproduct',
            name='amount',
            field=models.FloatField(),
        ),
    ]
