# Generated by Django 2.2.5 on 2019-09-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0008_auto_20190915_1844'),
        ('moonstuff', '0003_auto_20190926_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moonproduct',
            old_name='ore',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='moonproduct',
            unique_together={('moon', 'type')},
        ),
    ]
