# Generated by Django 2.2.5 on 2019-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0004_auto_20190927_0958'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moonproduct',
            index=models.Index(fields=['moon'], name='moonstuff_m_moon_id_0867e4_idx'),
        ),
    ]
