# Generated by Django 2.2.5 on 2019-09-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0004_auto_20190902_2132'),        
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveSolarSystem'),
        ),
    ]
