# Generated by Django 2.2.5 on 2019-09-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0005_auto_20190910_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moon',
            old_name='system_id',
            new_name='system',
        ),
    ]
