# Generated by Django 2.2.5 on 2019-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0005_auto_20190927_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='moon',
            name='income',
            field=models.FloatField(default=None, null=True),
        ),
    ]
