# Generated by Django 2.2.5 on 2019-09-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0006_auto_20190910_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evesde.EveSolarSystem'),
        ),
    ]
