# Generated by Django 2.2.5 on 2019-09-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0007_auto_20190911_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('view_moonstuff', 'Can access the moonstuff module.'), ('view_all_moons', 'Can view all moons'))},
        ),
    ]
