# Generated by Django 2.2.5 on 2019-09-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0008_auto_20190915_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'permissions': (('view_moonstuff', 'Can access the moonstuff module.'), ('view_all_moons', 'Can see all moons'))},
        ),
    ]
