# Generated by Django 3.1.6 on 2021-03-29 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveonline", "0014_auto_20210105_1413"),
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("authentication", "0017_remove_fleetup_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access the moonmining app"),
                    (
                        "extractions_access",
                        "Can access extractions and view owned moons",
                    ),
                    ("reports_access", "Can access reports"),
                    ("view_all_moons", "Can view all known moons"),
                    ("upload_moon_scan", "Can upload moon scans"),
                    ("add_corporation", "Can add mining corporations"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ready_time", models.DateTimeField(db_index=True)),
                ("auto_time", models.DateTimeField()),
                (
                    "value",
                    models.FloatField(
                        default=None,
                        help_text="Calculated value estimate",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("is_jackpot", models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MiningCorporation",
            fields=[
                (
                    "eve_corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mining_corporation",
                        serialize=False,
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="disabled corporations are excluded from the update process",
                    ),
                ),
                (
                    "last_update_at",
                    models.DateTimeField(
                        default=None,
                        help_text="time of last successful update",
                        null=True,
                    ),
                ),
                (
                    "last_update_ok",
                    models.BooleanField(
                        default=None,
                        help_text="True if the last update was successful",
                        null=True,
                    ),
                ),
                (
                    "character_ownership",
                    models.ForeignKey(
                        default=None,
                        help_text="character used to sync this corporation from ESI",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="authentication.characterownership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moon",
            fields=[
                (
                    "eve_moon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="known_moon",
                        serialize=False,
                        to="eveuniverse.evemoon",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        db_index=True,
                        default=None,
                        help_text="Calculated value estimate",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "rarity_class",
                    models.PositiveIntegerField(
                        choices=[
                            (0, ""),
                            (4, "R4"),
                            (8, "R8"),
                            (16, "R16"),
                            (32, "R32"),
                            (64, "R64"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "products_updated_at",
                    models.DateTimeField(
                        default=None,
                        help_text="Time the last moon survey was uploaded",
                        null=True,
                    ),
                ),
                (
                    "products_updated_by",
                    models.ForeignKey(
                        default=None,
                        help_text="User who uploaded the last moon survey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveOreType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eveuniverse.evetype",),
        ),
        migrations.CreateModel(
            name="Refinery",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "corporation",
                    models.ForeignKey(
                        help_text="Mining corporation that owns this refinery",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refineries",
                        to="moonmining.miningcorporation",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "moon",
                    models.OneToOneField(
                        default=None,
                        help_text="The moon this refinery is anchored at (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="refinery",
                        to="moonmining.moon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoonProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "moon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="moonmining.moon",
                    ),
                ),
                (
                    "ore_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="moonmining.eveoretype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="moonmining.extraction",
                    ),
                ),
                (
                    "ore_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="moonmining.eveoretype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extraction",
            name="refinery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extractions",
                to="moonmining.refinery",
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="started_by",
            field=models.ForeignKey(
                default=None,
                help_text="Eve character who started this extraction",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
    ]
