# Generated by Django 3.1.6 on 2021-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="auto_time",
            field=models.DateTimeField(
                default=None,
                help_text="when this extraction will be automatically fractured",
                null=True,
            ),
        ),
    ]
