# Generated by Django 3.1.6 on 2021-03-30 16:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("moonmining", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="canceled_at",
            field=models.DateTimeField(
                default=None, help_text="when this extraction was canceled", null=True
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="canceled_by",
            field=models.ForeignKey(
                default=None,
                help_text="Eve character who canceled this extraction",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="finished_at",
            field=models.DateTimeField(
                default=None, help_text="when this extraction finished", null=True
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="fractured_at",
            field=models.DateTimeField(
                default=None, help_text="when this extraction was fractured", null=True
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="fractured_by",
            field=models.ForeignKey(
                default=None,
                help_text="Eve character who fractured this extraction (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="when this extraction was started",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST", "started"),
                    ("CN", "canceled"),
                    ("FN", "finished"),
                    ("FR", "fractured"),
                ],
                default="ST",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extraction",
            name="auto_time",
            field=models.DateTimeField(
                help_text="when this extraction will be automatically fractured"
            ),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="is_jackpot",
            field=models.BooleanField(
                default=None,
                help_text="Whether this is a jackpot extraction (calculated)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="ready_time",
            field=models.DateTimeField(
                db_index=True, help_text="when this extraction is ready to be fractured"
            ),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="value",
            field=models.FloatField(
                default=None,
                help_text="Estimated value of this extraction (calculated)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
