# Generated by Django 3.1.6 on 2021-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST", "started"),
                    ("CN", "canceled"),
                    ("RD", "ready"),
                    ("CP", "completed"),
                    ("UN", "undefined"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
    ]
