# Generated by Django 3.1.6 on 2021-04-09 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moonmining", "0002_add_mining_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningledgerrecord",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mining_ledger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
