# Generated by Django 3.1.6 on 2021-04-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0002_miningactivity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="miningactivity",
            old_name="owner",
            new_name="refinery",
        ),
    ]
