# Generated by Django 3.1.6 on 2021-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0002_auto_20210330_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST", "started"),
                    ("CN", "canceled"),
                    ("FN", "finished"),
                    ("FR", "fractured"),
                    ("UN", "undefined"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
    ]
