# Generated by Django 3.1.6 on 2021-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0002_auto_20210402_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST", "started"),
                    ("CN", "canceled"),
                    ("RD", "ready"),
                    ("CP", "completed"),
                    ("UN", "undefined"),
                ],
                db_index=True,
                default="UN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="is_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="disabled corporations are excluded from the update process",
            ),
        ),
    ]
