# Generated by Django 3.1.6 on 2021-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0002_auto_20210406_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="decayes_at",
            field=models.DateTimeField(
                default=None, help_text="natural decay time", null=True
            ),
        ),
    ]
