# Generated by Django 3.1.6 on 2021-04-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0003_extraction_decayes_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extraction",
            name="decayes_at",
        ),
    ]
