# Generated by Django 3.1.6 on 2021-04-07 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moonmining", "0003_auto_20210407_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningLedgerRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(help_text="last_updated in ESI")),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        help_text="character that did the mining",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        help_text="corporation of the character at time data was recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "ore_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_ledger",
                        to="moonmining.eveoretype",
                    ),
                ),
                (
                    "refinery",
                    models.ForeignKey(
                        help_text="Refinery this mining activity was observed at",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_ledger",
                        to="moonmining.refinery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        help_text="user that did the mining (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MiningActivity",
        ),
    ]
