# Generated by Django 4.0.3 on 2022-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0004_add_permission_moon_ledgers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eveoretypeextras",
            name="refined_price",
        ),
        migrations.AddField(
            model_name="eveoretypeextras",
            name="current_price",
            field=models.FloatField(
                default=None,
                help_text="price used all price calculations with this type",
                null=True,
            ),
        ),
    ]
