# Generated by Django 3.2.9 on 2021-11-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0004_add_permission_moon_ledgers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access the moonmining app"),
                    (
                        "extractions_access",
                        "Can access extractions and view owned moons from own corporation",
                    ),
                    (
                        "view_alliance_extractions",
                        "Can view extractions from all refineries belonging to the alliance.",
                    ),
                    ("view_all_extractions", "Can view all extractions."),
                    ("reports_access", "Can access reports"),
                    ("view_all_moons", "Can view all known moons"),
                    ("upload_moon_scan", "Can upload moon scans"),
                    ("add_refinery_owner", "Can add refinery owner"),
                    ("view_moon_ledgers", "Can view moon ledgers"),
                ),
            },
        ),
    ]
