# Generated by Django 3.1.6 on 2021-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0004_eveoretyperefinedprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="refinery",
            name="ledger_last_update_at",
            field=models.DateTimeField(
                default=None,
                help_text="last successful update of mining ledger",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="refinery",
            name="ledger_last_update_ok",
            field=models.BooleanField(
                default=None,
                help_text="True if the last update of the mining ledger was successful",
                null=True,
            ),
        ),
    ]
