# Generated by Django 4.0.3 on 2022-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0005_make_pricing_more_flexible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("default", "grey"),
                            ("primary", "dark blue"),
                            ("success", "green"),
                            ("info", "light blue"),
                            ("warning", "orange"),
                            ("danger", "red"),
                        ],
                        default="default",
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
