# Generated by Django 4.0.3 on 2022-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0005_make_pricing_more_flexible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moon",
            name="rarity_class",
            field=models.PositiveIntegerField(
                choices=[
                    (0, ""),
                    (4, "R 4"),
                    (8, "R 8"),
                    (16, "R16"),
                    (32, "R32"),
                    (64, "R64"),
                ],
                default=0,
            ),
        ),
    ]
