# Generated by Django 3.1.6 on 2021-04-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0006_auto_20210415_1306"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveOreTypeExtras",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refined_price",
                    models.FloatField(
                        default=None,
                        help_text="price calculated as sum of prices for refined materials",
                        null=True,
                    ),
                ),
                (
                    "ore_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="moonmining.eveoretype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EveOreTypeExtra",
        ),
    ]
