# Generated by Django 4.0.3 on 2022-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0006_alter_moon_rarity_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="eveoretypeextras",
            name="pricing_method",
            field=models.CharField(
                choices=[
                    ("UN", "Unknown"),
                    ("EC", "Eve client"),
                    ("RP", "Reprocessed materials"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
    ]
