# Generated by Django 3.1.6 on 2021-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0006_auto_20210331_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="details",
            field=models.JSONField(default=dict),
        ),
    ]
