# Generated by Django 4.0.3 on 2022-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0006_add_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="style",
            field=models.CharField(
                choices=[
                    ("default", "grey"),
                    ("primary", "dark blue"),
                    ("success", "green"),
                    ("info", "light blue"),
                    ("warning", "orange"),
                    ("danger", "red"),
                ],
                default="default",
                max_length=16,
            ),
        ),
    ]
