# Generated by Django 3.1.6 on 2021-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moonmining", "0008_remove_notification_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
